### ISSUE TITLE
"bash" where we don't want it.

### ISSUE THREAD

**Issue by snori74** [livialima/linuxupskillchallenge#1]
The recent big PR that I approved included at least two instances where the previous formatting was replaced with "3backticks bash". Looks fine I. GitHub and new Reddit, but not in oldreddit which quite a few people use.

**Comment by janbue** [comment]
What solution would you propose, just remove the bash part?

**Comment by snori74** [comment]
Most likely simply revert to whatever was there before - it's was fine for the last year. Each commit has a 'diff' where it shows before and after.

**Comment by janbue** [comment]
Should be fixed now
PR #117 in old repo, commit is called "markdown linting, typos and copyright updated"

This commit https://github.com/snori74/linuxupskillchallenge/pull/117/commits/60049f7790b1913681248cc65a5722fe15d2be58
