### ISSUE TITLE
Build script error (LaTeX): File `pdftexcmds.sty` not found

### ISSUE THREAD

**Issue by DatBoi-BP** [livialima/linuxupskillchallenge#16]
When running the Build bash script, the following message is output in the terminal, despite the prerequisites (commented within the script) having been met. Perhaps the missing file is a simple one that can be included in this repo?

```
Error producing PDF.
! LaTeX Error: File `pdftexcmds.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.108 \RequirePackage{pdftexcmds}[2009/04/10]
```

**Comment by livialima** [comment]
Working on build dependencies
