### ISSUE TITLE
Day 15 - correction request

### ISSUE THREAD

**Issue by robinovitch61** [livialima/linuxupskillchallenge#19]
**Type of error**
 - Dead Link/Technical error

**Describe the error**
The [neofetch third party ppa has been deprecated](https://github.com/dylanaraps/neofetch/wiki/Installation#ubuntu-1704-and-up)

```
ubuntu@ip-172-31-24-204:~$ sudo add-apt-repository ppa:dawidd0811/neofetch
Cannot add PPA: 'ppa:~dawidd0811/ubuntu/neofetch'.
The user named '~dawidd0811' has no PPA named 'ubuntu/neofetch'
Please choose from the following available PPAs:
```

**Expected behavior**
Day 15 recommends adding this PPA, but it no longer exists.

**Proposed solution/correction**
Maybe add a new PPA, or just indicate that this one is now deprecated.

**Additional context**
Thank you! :)

**Comment by livialima** [comment]
Looking for new PPA candidates to replace neofetch in the example.
May need to redesign the lesson.

**Comment by livialima** [comment]
Found a PPA still supporting Neofetch and updated the lesson.

**Comment by robinovitch61** [comment]
Awesome! Thank you for your continued work and care!
