### ISSUE TITLE
Day 0 - Add Oracle Free Cloud Tier

### ISSUE THREAD

**Issue by RuthlessRuler** [livialima/linuxupskillchallenge#20]
Please always specify the day of the lesson (i.e. Day 17, Day 0 AWS) in the title of the issue.

**Describe the feature or topic you'd like see in the lesson**
Oracle Free Tier is very nice offering, and i think it can be a good point to start.

**Describe alternatives you've considered**
None 

**Additional context**
https://www.oracle.com/cloud/free/

**Comment by livialima** [comment]
I'm giving it a lab run right now. It's a nice offering indeed, but not as friendly to absolute beginners, I would say.
It will get a tutorial for Day 0, stay tuned and thanks for the suggestion.
