### ISSUE TITLE
Day 2 - correction request (Typo)

### ISSUE THREAD

**Issue by winnetkard** [livialima/linuxupskillchallenge#21]
**Type of error**
 - Typo

**Describe the error**
Under 'Your Tasks Today', 
move 'about' the directory -> move 'around' the directory

**Proposed solution/correction**
'about' updated to 'around'

**Comment by livialima** [comment]
Corrected. Thanks for catching that @winnetkard

**Comment by livialima** [comment]
Corrected. Thanks for catching that @winnetkard
