### ISSUE TITLE
Day 6 - Address confusion between vi and vim reported by learners

### ISSUE THREAD

**Issue by kraker** [livialima/linuxupskillchallenge#33]
## Describe the feature or topic you'd like see in the lesson

This lesson first has users check if `vi` is installed on their system. And it usually is by default on most major Linux distributions. But then the rest of the lesson uses `vim` which isn't always installed (or aliased) by default. This can cause some confusion if new learners are expecting `vim` commands to work. 

## Describe alternatives you've considered

Unless we're going to have learners install `vim` on their systems at the beginning if the lesson we should use `vi` throughout. My opinion, is because `vi` is most often installed by default it will almost always be available. And since they are just learning the basic vi modes and motions which also applies to vim, there's not a distinct reason to have them install vim or explicitly use vim.

Counter to this is that `vimtutor` is referenced later on in the lesson. We could have learners install vim at this point in the lesson, or to reduce overall confusion just have learners install vim at the beginning of the lesson. In either case we then need to have documented support for installing vim on all major Linux distributions which could add maintenance overhead to this lesson since we would then need to maintain our own version of `vim` installation documentation.

Another option would be to move vim installation and `vimtutor` to the **extension** section of the lesson. 

## Additional context

Copied from user's comment in the Discord server `#suggestions` channel:

> I had some trouble on Day 6, it says to run vi which exists on my Debian 11 VPS . It then says to run vim testfile, but my system doesn't have vim , only vi which seems to run vim. also, further down in the lesson it says vimtutor should always be installed, on my VPS it was not

**Comment by kraker** [comment]
@livialima I'm planning on submitting a PR to address this when I can find the time. Feel free to "assign" this issue to me if you want.

**Comment by kraker** [comment]
## User's issue replicated on Debian 11 test box

```bash
vagrant@debian11:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
vagrant@debian11:~$ vim testfile
-bash: vim: command not found
```

It would appear that in this case `vi` is actually a version of `vim`. 

```bash
vagrant@debian11:~$ vi --version | head
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
...
vagrant@debian11:~$ which vi
/usr/bin/vi
vagrant@debian11:~$ realpath /usr/bin/vi
/usr/bin/vim.tiny
```

**Comment by livialima** [comment]
Thank you so much for catching it, @kraker !
I really appreciate your help, the issue is yours 😎

**Comment by matt-kita** [comment]
Since vim is mostly backwards-compatible with vi, you could also consider 
`echo "alias vim='vi'" >> ~/.bashrc`
instead of vim installation.

**Comment by kraker** [comment]
Thanks for the alias suggestion @matt-kita, I updated PR #34 with changes.
