### ISSUE TITLE
https://linuxupskillchallenge.org won't load

### ISSUE THREAD

**Issue by maaneeack** [livialima/linuxupskillchallenge#4]
**Describe the bug**
https version of the site fails to load, http version will

**To Reproduce**
1. Go to 'https://linuxupskillchallenge.com'
2. Click on address bar after it fails to load and remove the S in https
3. Site will now load

**Expected behavior**
Going to https link should load

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium Edge
 - Version: 90.0.818.42 64bit

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by livialima** [comment]
I've been moving the domain to a host of my own since snori74's passing. Https is in the plans, should be done before the end of the month.

**Comment by livialima** [comment]
Resolved. SSL certificated in place, we can use HTTPS now.
