### ISSUE TITLE
Day 0-21 - feature request: create a community on Lemmy

### ISSUE THREAD

**Issue by esaporski** [livialima/linuxupskillchallenge#40]
**Describe the feature or topic you'd like see in the lesson**
Because Reddit is a mess right now, it would be nice to have this community on **Lemmy** as well. Another alternative is **kbin**, but I'd rather have it on [lemmy.world](https://lemmy.world/).

**Additional context**
Reddit is maliciously changing its API pricing, killing 3rd-party apps and making everyone angry:
https://arstechnica.com/gadgets/2023/06/api-pricing-protests-caused-reddit-to-crash-for-3-hours/

**Comment by livialima** [comment]
Request made: https://programming.dev/post/2385364

**Comment by Ategon** [comment]
(P.D admin here) Community has been made. It is possible to automate posting and ive got a bot Ive worked on that can do that although need to push out an update to support the new lemmy version (or it can be forked). Update should be coming sometime this week https://github.com/Ategon/Lemmy-Frank-Bot

**Comment by livialima** [comment]
Thanks for the bot suggestion, @Ategon! I'll be using it.

**Comment by livialima** [comment]
Community created at [programming.dev](https://programming.dev/c/linuxupskillchallenge@programming.dev)
