### ISSUE TITLE
Day 4 - correction request - Dead link

### ISSUE THREAD

**Issue by nikitas-theo** [livialima/linuxupskillchallenge#48]
**Type of error**
 - Dead Link

**Describe the error**
The following link is broken on [Day 4](https://linuxupskillchallenge.org/04/), on **Resources** section, second bullet point:
[DNF vs APT: Similarities and Differences Analyzed!](https://embeddedinventor.com/dnf-vs-apt-similarities-and-differences-analyzed/)

**Comment by matt-kita** [comment]
@livialima
"Investigation" shows, it changed to: https://embeddedinventor.com/dnf-vs-apt-similarities-and-diffs-analyzed
