### ISSUE TITLE
Day 8 - broken link

### ISSUE THREAD

**Issue by puneetlath** [livialima/linuxupskillchallenge#64]
**Type of error**
 - Dead Link

**Describe the error**
The [“Santiago”: Find the secret combination](https://sadservers.com/scenario/santiago) SadServers challenge on day 8 is a dead link. It doesn't look like this challenge exists on SadServers anymore. 

**Expected behavior**
That the link works. 

**Proposed solution/correction**
The bullet for this challenge should be removed from the page.

**Comment by livialima** [comment]
[Scenario has been deactivated](https://github.com/fduran/sadservers/issues/10)
